/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./Cyber-Defence/Signatures/yara/authenticode_anomalies.yara"
include "./Cyber-Defence/Signatures/yara/badwinmail.yara"
include "./Cyber-Defence/Signatures/yara/package_manager.yara"
include "./Cyber-Defence/Signatures/yara/red_leaves.yara"
include "./Cyber-Defence/Signatures/yara/sakula.yara"
