/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./DidierStevensSuite/IOS_canary.yara"
include "./DidierStevensSuite/JPEG_EXIF_Contains_eval.yara"
include "./DidierStevensSuite/contains_pe_file.yara"
include "./DidierStevensSuite/contains_vbe_file.yara"
include "./DidierStevensSuite/maldoc.yara"
include "./DidierStevensSuite/pe_file_pyinstaller.yara"
include "./DidierStevensSuite/peid-userdb-rules-with-pe-module.yara"
include "./DidierStevensSuite/peid-userdb-rules-without-pe-module.yara"
include "./DidierStevensSuite/rtf.yara"
include "./DidierStevensSuite/vba.yara"
