/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./f0wl_yara_rules/linux/crypter/ezuri_revised.yar"
include "./f0wl_yara_rules/linux/ransomware/revil_linux.yar"
include "./f0wl_yara_rules/other/ESXi/blackmatter_linux_decryptor.yar"
include "./f0wl_yara_rules/other/ESXi/blackmatter_linux_encryptor.yar"
include "./f0wl_yara_rules/other/ESXi/esxi_commands_ransomware.yar"
include "./f0wl_yara_rules/windows/banker/danabot_main.yar"
include "./f0wl_yara_rules/windows/crypter/huan_crypter.yar"
include "./f0wl_yara_rules/windows/crypter/zipExec_crypter.yar"
include "./f0wl_yara_rules/windows/ransomware/deathransom.yar"
include "./f0wl_yara_rules/windows/ransomware/germanwiper.yar"
include "./f0wl_yara_rules/windows/ransomware/mountLockerV2_unpacked.yar"
include "./f0wl_yara_rules/windows/ransomware/netwalker.yar"
include "./f0wl_yara_rules/windows/ransomware/wannacry.yar"
include "./f0wl_yara_rules/windows/uac/ICMLuaUtil_UACMe_M41.yar"
