/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./fr0gger_Yara_Unprotect/Detect_DisableAV_Unprotect.yar"
include "./fr0gger_Yara_Unprotect/Detect_DisableSEC_Unprotect.yar"
include "./fr0gger_Yara_Unprotect/Detect_InjectCode_Unprotect.yar"
include "./fr0gger_Yara_Unprotect/Detect_Monitoring_Unprotect.yar"
include "./fr0gger_Yara_Unprotect/Detect_Sandbox_Unprotect.yar"
include "./fr0gger_Yara_Unprotect/anti_av.yar"
include "./fr0gger_Yara_Unprotect/anti_debugging.yar"
include "./fr0gger_Yara_Unprotect/anti_monitoring.yar"
include "./fr0gger_Yara_Unprotect/anti_sandboxing.yar"
include "./fr0gger_Yara_Unprotect/compiler.yar"
include "./fr0gger_Yara_Unprotect/findcrypt.yar"
include "./fr0gger_Yara_Unprotect/network_evasion.yar"
include "./fr0gger_Yara_Unprotect/packers.yar"
include "./fr0gger_Yara_Unprotect/process_manipulating.yar"
