/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./imp0rtp3_yara-rules/2020-06-06 TSCoockie/yar.yar"
include "./imp0rtp3_yara-rules/2020-06-07 Roothelper/yar.yar"
include "./imp0rtp3_yara-rules/2021-06-06 TSCoockie/yar.yar"
include "./imp0rtp3_yara-rules/2021-06-07 Roothelper/yar.yar"
include "./imp0rtp3_yara-rules/2021-06-08 acmi botnet/yar.yar"
include "./imp0rtp3_yara-rules/2021-06-10 Sborka/yar.yar"
include "./imp0rtp3_yara-rules/2021-07-17 Candiru/yar.yar"
include "./imp0rtp3_yara-rules/2021-08-12 Tetris/fingerprint2.yar"
include "./imp0rtp3_yara-rules/2021-08-12 Tetris/tetris.yar"
include "./imp0rtp3_yara-rules/2021-08-12 Tetris/tetris_advanced.yar"
include "./imp0rtp3_yara-rules/2021-08-25 JS obfuscator/yara.yar"
include "./imp0rtp3_yara-rules/2021-11-25 SoWaT/sowat.yar"
