/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./indicators/Blogs/New URSNIF Targeting Italy and US/ursnif.yar"
include "./indicators/Blogs/Shining a Light on Xenon/xenon-crypter.yar"
include "./indicators/Fidelis Threat Advisory/FTA-1021/apt_derusbi_Blog_and_Github.yar"
include "./indicators/yararules/AlienSpy.yar"
include "./indicators/yararules/DarkComet.yar"
include "./indicators/yararules/crime_win32_exe_rat_netwire.yar"
include "./indicators/yararules/crime_win_PWS_Fareit.yar"
include "./indicators/yararules/inocnation.yar"
include "./indicators/yararules/ursnif.yar"
include "./indicators/yararules/xenon-crypter.yar"
