/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./intezer_yara-rules/APT15.yar"
include "./intezer_yara-rules/AgeLocker.yar"
include "./intezer_yara-rules/ChinaZ_Managers.yar"
include "./intezer_yara-rules/DarkComet.yar"
include "./intezer_yara-rules/Doki_Attack.yar"
include "./intezer_yara-rules/EvilGnome.yar"
include "./intezer_yara-rules/Gh0stRAT.yar"
include "./intezer_yara-rules/GreedyAntd.yar"
include "./intezer_yara-rules/HiddenWasp.yar"
include "./intezer_yara-rules/IPStorm.yar"
include "./intezer_yara-rules/Iranian_Wipers.yar"
include "./intezer_yara-rules/Lazarus_2020.yar"
include "./intezer_yara-rules/NexePirateSteal.yar"
include "./intezer_yara-rules/QNAPCrypt.yar"
include "./intezer_yara-rules/RedDelta.yar"
include "./intezer_yara-rules/Rekoobe.yar"
include "./intezer_yara-rules/RussianAPT.yar"
include "./intezer_yara-rules/Trickbot.yar"
include "./intezer_yara-rules/WatchBog.yar"
