/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./malice-plugin_yara/rules/JPEG_EXIF_Contains_eval.yara"
include "./malice-plugin_yara/rules/avdetect.yar"
include "./malice-plugin_yara/rules/contains_pe_file.yara"
include "./malice-plugin_yara/rules/contains_vbe_file.yara"
include "./malice-plugin_yara/rules/dbgdetect.yar"
include "./malice-plugin_yara/rules/embedded.yar"
include "./malice-plugin_yara/rules/maldoc.yara"
include "./malice-plugin_yara/rules/pe_file_pyinstaller.yara"
include "./malice-plugin_yara/rules/peid-userdb-rules-with-pe-module.yara"
include "./malice-plugin_yara/rules/rats.yar"
include "./malice-plugin_yara/rules/sandboxdetect.yar"
include "./malice-plugin_yara/rules/userdb_panda.yar"
