/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./prolsen_yara-rules/cves/CVE_2013_1347/CVE_2013_1347.yara"
include "./prolsen_yara-rules/documents/misc_rules.yara"
include "./prolsen_yara-rules/dropper_tool/dropper_tools.yara"
include "./prolsen_yara-rules/memory/memory.yara"
include "./prolsen_yara-rules/pcaps/PCAPs.yara"
include "./prolsen_yara-rules/persistence/LNK_files/LNK_files.yara"
include "./prolsen_yara-rules/pos/pos_malware.yara"
include "./prolsen_yara-rules/pos/pos_memory.yara"
include "./prolsen_yara-rules/rats/rats.yara"
include "./prolsen_yara-rules/remote_shells/remote_shells.yara"
include "./prolsen_yara-rules/trojans/misc_trojans.yara"
include "./prolsen_yara-rules/web/web_log_review.yara"
include "./prolsen_yara-rules/web/web_shells.yara"
