/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./securitymagic_yara/Jupyter Malware/JupyterDll.yar"
include "./securitymagic_yara/Jupyter Malware/JupyterPS.yar"
include "./securitymagic_yara/Jupyter Malware/Jupyter_dll2.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker_0322.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker_dropper.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker_packer.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker_packer2.yar"
include "./securitymagic_yara/Jupyter Malware/solarmarker_packer3.yar"
include "./securitymagic_yara/Possible DLL Hijacking/wwlib.yar"
include "./securitymagic_yara/Suspicious Powershell/Suspicious_PowerShell_Strings.yar"
include "./securitymagic_yara/emotet/emotet_dll.yar"
include "./securitymagic_yara/maldocs/Word_PS_Downloader.yar"
include "./securitymagic_yara/obfuscation/suspicious_scripts.yar"
include "./securitymagic_yara/pws/possible_redline.yar"
include "./securitymagic_yara/rats/rat_detection.yar"
include "./securitymagic_yara/vbs/vbs_downloader_jan2021.yar"
