/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./tenable_yara-rules/generic/elf_format.yar"
include "./tenable_yara-rules/malware/cerber3.yar"
include "./tenable_yara-rules/malware/hived.yara"
include "./tenable_yara-rules/malware/kaiten.yar"
include "./tenable_yara-rules/malware/venom.yar"
include "./tenable_yara-rules/webshells/fopo.yar"
include "./tenable_yara-rules/webshells/generic_jsp.yar"
include "./tenable_yara-rules/webshells/obfuscated_php.yar"
include "./tenable_yara-rules/webshells/pas_web_kit.yar"
include "./tenable_yara-rules/webshells/pbot.yar"
