/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./tjnel_yara_repo/ransomware/crime_win_ransom_anubi.yara"
include "./tjnel_yara_repo/trojans/arkei_stealer.yara"
include "./tjnel_yara_repo/trojans/darksky_http.yara"
include "./tjnel_yara_repo/trojans/diamond_fox.yara"
include "./tjnel_yara_repo/trojans/flusihoc.yara"
include "./tjnel_yara_repo/trojans/kardon_loader.yara"
include "./tjnel_yara_repo/trojans/konni.yara"
include "./tjnel_yara_repo/trojans/merocota.yara"
include "./tjnel_yara_repo/trojans/ovidiy.yara"
