/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./volexity_threat-intel/threat-intel/2021/2021-03-02 - Operation Exchange Marauder/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2021/2021-05-27 - Suspected APT29 Operation Launches Election Fraud Themed Phishing Campaigns/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2021/2021-08-17 - InkySquid Part 1/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2021/2021-08-24 - InkySquid Part 2/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2021/2021-12-06 - XEGroup/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-03-22 GIMMICK/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-06-02 Active Exploitation Of Confluence 0-day/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-06-15 DriftingCloud - Zero-Day Sophos Firewall Exploitation and an Insidious Breach/indicators/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-07-28 SharpTongue SharpTongue Deploys Clever Mail-Stealing Browser Extension SHARPEXT/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-08-10 Mass exploitation of (Un)authenticated Zimbra RCE CVE-2022-27925/yara.yar"
include "./volexity_threat-intel/threat-intel/2022/2022-12-01 Buyer Beware - Fake Cryptocurrency Applications Serving as Front for AppleJeus Malware/yara.yar"
