/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./wrayjustin_yaids/tests/test_A.yar"
include "./wrayjustin_yaids/tests/test_B.yar"
include "./wrayjustin_yaids/tests/test_C.yar"
include "./wrayjustin_yaids/tests/test_D.yar"
include "./wrayjustin_yaids/tests/test_F.yar"
