/*
Generated by Yara-Rules
On 25-01-2023
*/
include "./x64dbg_yarasigs/Old_Internal_PEiD.yara"
include "./x64dbg_yarasigs/crypto_signatures.yara"
include "./x64dbg_yarasigs/packer.yara"
include "./x64dbg_yarasigs/packer_compiler_signatures.yara"
include "./x64dbg_yarasigs/rich.yara"
